/**
 * Sync repo/repo.json from package/*.json and generate static HTML pages.
 *
 * Usage: deno task gen-site (from repo-tools or workspace root)
 */
import { dirname, fromFileUrl, join } from '@std/path'
import { ensureDir } from '@std/fs'

const GENERATED_MARKER =
  '<!-- generated by repo-tools/scripts/gen-site.ts; do not edit -->'

const scriptDir = dirname(fromFileUrl(import.meta.url))
const repoRoot = join(scriptDir, '../../repo')
const packageDir = join(repoRoot, 'package')
const repoJsonPath = join(repoRoot, 'repo.json')
const indexHtmlPath = join(repoRoot, 'index.html')
const pkgDenoJsonPath = join(scriptDir, '../../pkg/deno.json')

const GITHUB_BLOB_BASE =
  'https://github.com/patdx/dotfiles-public/blob/main/repo/package'

interface RepoListing {
  $schema?: string
  version?: number
  packages: string[]
  min_cli_version?: string
}

function escapeHtml(text: string): string {
  return text
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
}

function renderCmdBlock(escapedCode: string): string {
  return `<div class="cmd">
        <code>${escapedCode}</code>
        <button type="button" class="copy-install">Copy</button>
      </div>`
}

const pkgVersion = (
  JSON.parse(await Deno.readTextFile(pkgDenoJsonPath)) as { version: string }
).version
const CLI_SPEC = `jsr:@patdx/pkg@${pkgVersion}`
const CLI_INSTALL = `deno install -g -A -n ppkg ${CLI_SPEC}`
const CLI_INSTALL_FRESH =
  `deno install -g -A -n ppkg --min-dep-age=0 ${CLI_SPEC}`

function installCommand(name: string): string {
  return `ppkg add ${name}`
}

function removeCommand(name: string): string {
  return `ppkg remove ${name}`
}

function installOneLiner(name: string): string {
  return `deno run -A --reload ${CLI_SPEC} add ${name}`
}

function htmlHead(title: string): string {
  return `<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${title}</title>
    <link rel="stylesheet" href="/site.css" />
  </head>`
}

function renderIndex(packages: string[]): string {
  const list = packages
    .map((name) =>
      `<li><a href="/package/${escapeHtml(name)}">${escapeHtml(name)}</a></li>`
    )
    .join('\n        ')
  const example = packages[0] ?? 'caddy'
  return `${GENERATED_MARKER}
<!DOCTYPE html>
<html lang="en">
  ${htmlHead('@patdx/pkg catalog')}
  <body>
    <main>
      <h1>@patdx/pkg</h1>
      <p>
        Install binary packages on Linux and macOS from this catalog or any URL.
        The local CLI is <code>ppkg</code> (JSR package
        <a href="https://jsr.io/@patdx/pkg">@patdx/pkg</a>).
        Default remote:
        <a href="https://repo.pmil.me">https://repo.pmil.me</a>
      </p>
      <p>Install the CLI once (ensure <code>~/.deno/bin</code> is on your <code>PATH</code>):</p>
      ${renderCmdBlock(escapeHtml(CLI_INSTALL))}
      <p>
        If Deno blocks a freshly published version
        (<a href="https://docs.deno.com/go/minimum-dependency-age">minimum dependency age</a>,
        default 24h), retry with <code>--min-dep-age=0</code>:
      </p>
      ${renderCmdBlock(escapeHtml(CLI_INSTALL_FRESH))}
      <p>Example install:</p>
      ${renderCmdBlock(escapeHtml(installCommand(example)))}
      <p>Example remove:</p>
      ${renderCmdBlock(escapeHtml(removeCommand(example)))}
      <p>One-liner without a global install:</p>
      ${renderCmdBlock(escapeHtml(installOneLiner(example)))}
      <h2>Packages</h2>
      <ul>
        ${list}
      </ul>
      <div class="links">
        <a href="/repo.json">repo.json</a>
        <a href="https://jsr.io/@patdx/pkg">jsr:@patdx/pkg</a>
      </div>
    </main>
    <script type="module" src="/site.js"></script>
  </body>
</html>
`
}

function renderPackagePage(name: string): string {
  const manifestPath = `/package/${name}.json`
  const githubUrl = `${GITHUB_BLOB_BASE}/${name}.json`
  return `${GENERATED_MARKER}
<!DOCTYPE html>
<html lang="en">
  ${htmlHead(`${escapeHtml(name)} · @patdx/pkg`)}
  <body>
    <main>
      <h1>${escapeHtml(name)}</h1>
      <p>
        First-time setup: install the <code>ppkg</code> CLI once
        (ensure <code>~/.deno/bin</code> is on your <code>PATH</code>;
        see <a href="/">catalog</a> for more):
      </p>
      ${renderCmdBlock(escapeHtml(CLI_INSTALL))}
      <p>Then install this package:</p>
      ${renderCmdBlock(escapeHtml(installCommand(name)))}
      <p>Remove:</p>
      ${renderCmdBlock(escapeHtml(removeCommand(name)))}
      <p>Or without installing the CLI:</p>
      ${renderCmdBlock(escapeHtml(installOneLiner(name)))}
      <div class="links">
        <a href="${escapeHtml(manifestPath)}">Manifest JSON</a>
        <a href="${escapeHtml(githubUrl)}">Edit on GitHub</a>
      </div>
      <nav><a href="/">← All packages</a></nav>
    </main>
    <script type="module" src="/site.js"></script>
  </body>
</html>
`
}

async function listPackageNames(): Promise<string[]> {
  const names: string[] = []
  for await (const entry of Deno.readDir(packageDir)) {
    if (!entry.isFile || !entry.name.endsWith('.json')) continue
    names.push(entry.name.slice(0, -'.json'.length))
  }
  names.sort((a, b) => a.localeCompare(b))
  return names
}

async function syncRepoJson(packages: string[]): Promise<void> {
  const existing = JSON.parse(
    await Deno.readTextFile(repoJsonPath),
  ) as RepoListing

  const next: RepoListing = {
    $schema: existing.$schema,
    version: existing.version,
    packages,
    min_cli_version: existing.min_cli_version,
  }

  await Deno.writeTextFile(
    repoJsonPath,
    `${JSON.stringify(next, null, 2)}\n`,
  )
}

async function pruneStaleHtml(packages: Set<string>): Promise<void> {
  try {
    for await (const entry of Deno.readDir(packageDir)) {
      if (!entry.isFile || !entry.name.endsWith('.html')) continue
      const name = entry.name.slice(0, -'.html'.length)
      const path = join(packageDir, entry.name)
      if (packages.has(name)) continue
      const text = await Deno.readTextFile(path)
      if (!text.includes(GENERATED_MARKER)) continue
      await Deno.remove(path)
      console.log(`Removed stale ${path}`)
    }
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error
  }
}

const packages = await listPackageNames()
await syncRepoJson(packages)
await Deno.writeTextFile(indexHtmlPath, renderIndex(packages))
await ensureDir(packageDir)

for (const name of packages) {
  await Deno.writeTextFile(
    join(packageDir, `${name}.html`),
    renderPackagePage(name),
  )
}

await pruneStaleHtml(new Set(packages))

console.log(`Synced ${packages.length} packages into ${repoJsonPath}`)
console.log(`Wrote ${indexHtmlPath}`)
console.log(`Wrote ${packages.length} pages under ${packageDir}`)
